import { ConnectionRule } from "../../types/circuit";

export const starDeltaRules: ConnectionRule[] = [
  // --- 3-PHASE POWER CIRCUIT ---
  {
    id: "rule-p1",
    from: "L1",
    to: "MCB-L1-IN",
    required: true,
    description: "Sambungkan Bekalan L1 ke MCB L1 IN",
    category: "POWER",
  },
  {
    id: "rule-p2",
    from: "L2",
    to: "MCB-L2-IN",
    required: true,
    description: "Sambungkan Bekalan L2 ke MCB L2 IN",
    category: "POWER",
  },
  {
    id: "rule-p3",
    from: "L3",
    to: "MCB-L3-IN",
    required: true,
    description: "Sambungkan Bekalan L3 ke MCB L3 IN",
    category: "POWER",
  },
  {
    id: "rule-p4",
    from: "MCB-L1-OUT",
    to: "KM1-L1",
    required: true,
    description: "Sambungkan MCB L1 OUT ke Kontaktor Utama KM1 L1",
    category: "POWER",
  },
  {
    id: "rule-p5",
    from: "MCB-L2-OUT",
    to: "KM1-L2",
    required: true,
    description: "Sambungkan MCB L2 OUT ke Kontaktor Utama KM1 L2",
    category: "POWER",
  },
  {
    id: "rule-p6",
    from: "MCB-L3-OUT",
    to: "KM1-L3",
    required: true,
    description: "Sambungkan MCB L3 OUT ke Kontaktor Utama KM1 L3",
    category: "POWER",
  },
  {
    id: "rule-p7",
    from: "KM1-T1",
    to: "OLR-L1-IN",
    required: true,
    description: "Sambungkan KM1 T1 ke Relay Beban Lampau OLR L1 IN",
    category: "POWER",
  },
  {
    id: "rule-p8",
    from: "KM1-T2",
    to: "OLR-L2-IN",
    required: true,
    description: "Sambungkan KM1 T2 ke Relay Beban Lampau OLR L2 IN",
    category: "POWER",
  },
  {
    id: "rule-p9",
    from: "KM1-T3",
    to: "OLR-L3-IN",
    required: true,
    description: "Sambungkan KM1 T3 ke Relay Beban Lampau OLR L3 IN",
    category: "POWER",
  },
  {
    id: "rule-p10",
    from: "OLR-T1-OUT",
    to: "MOTOR-U1",
    required: true,
    description: "Sambungkan OLR T1 OUT ke Terminal Motor U1",
    category: "POWER",
  },
  {
    id: "rule-p11",
    from: "OLR-T2-OUT",
    to: "MOTOR-V1",
    required: true,
    description: "Sambungkan OLR T2 OUT ke Terminal Motor V1",
    category: "POWER",
  },
  {
    id: "rule-p12",
    from: "OLR-T3-OUT",
    to: "MOTOR-W1",
    required: true,
    description: "Sambungkan OLR T3 OUT ke Terminal Motor W1",
    category: "POWER",
  },
  {
    id: "rule-p13",
    from: "KM1-L1",
    to: "KM3-L1",
    required: true,
    description: "Sambungkan Fasa 1 dari KM1 L1 ke KM3 L1 (Delta)",
    category: "POWER",
  },
  {
    id: "rule-p14",
    from: "KM1-L2",
    to: "KM3-L2",
    required: true,
    description: "Sambungkan Fasa 2 dari KM1 L2 ke KM3 L2 (Delta)",
    category: "POWER",
  },
  {
    id: "rule-p15",
    from: "KM1-L3",
    to: "KM3-L3",
    required: true,
    description: "Sambungkan Fasa 3 dari KM1 L3 ke KM3 L3 (Delta)",
    category: "POWER",
  },
  {
    id: "rule-p16",
    from: "KM3-T1",
    to: "MOTOR-W2",
    required: true,
    description: "Sambungkan KM3 T1 ke Motor Terminal W2",
    category: "POWER",
  },
  {
    id: "rule-p17",
    from: "KM3-T2",
    to: "MOTOR-U2",
    required: true,
    description: "Sambungkan KM3 T2 ke Motor Terminal U2",
    category: "POWER",
  },
  {
    id: "rule-p18",
    from: "KM3-T3",
    to: "MOTOR-V2",
    required: true,
    description: "Sambungkan KM3 T3 ke Motor Terminal V2",
    category: "POWER",
  },
  {
    id: "rule-p19",
    from: "KM3-T1",
    to: "KM2-L1",
    required: true,
    description: "Sambungkan KM3 T1 ke KM2 L1 (Litar Bintang)",
    category: "POWER",
  },
  {
    id: "rule-p20",
    from: "KM3-T2",
    to: "KM2-L2",
    required: true,
    description: "Sambungkan KM3 T2 ke KM2 L2 (Litar Bintang)",
    category: "POWER",
  },
  {
    id: "rule-p21",
    from: "KM3-T3",
    to: "KM2-L3",
    required: true,
    description: "Sambungkan KM3 T3 ke KM2 L3 (Litar Bintang)",
    category: "POWER",
  },
  {
    id: "rule-p22",
    from: "KM2-T1",
    to: "KM2-T2",
    required: true,
    description: "Pintas Terminal KM2 T1 ke T2 (Pintas Bintang / Star Bridge)",
    category: "POWER",
  },
  {
    id: "rule-p23",
    from: "KM2-T2",
    to: "KM2-T3",
    required: true,
    description: "Pintas Terminal KM2 T2 ke T3 (Pintas Bintang / Star Bridge)",
    category: "POWER",
  },

  // --- CONTROL CIRCUIT ---
  {
    id: "rule-c1",
    from: "MCB-L1-OUT",
    to: "OLR-95",
    required: true,
    description: "Sambungkan Kawalan Fasa L1 ke OLR Contact 95 NC",
    category: "CONTROL",
  },
  {
    id: "rule-c2",
    from: "OLR-96",
    to: "STOP-IN",
    required: true,
    description: "Sambungkan OLR Contact 96 NC ke Butang STOP IN",
    category: "CONTROL",
  },
  {
    id: "rule-c3",
    from: "STOP-OUT",
    to: "START-IN",
    required: true,
    description: "Sambungkan Butang STOP OUT ke Butang START IN",
    category: "CONTROL",
  },
  {
    id: "rule-c4",
    from: "START-OUT",
    to: "KM1-A1",
    required: true,
    description: "Sambungkan Butang START OUT ke Gelung KM1 A1",
    category: "CONTROL",
  },
  {
    id: "rule-c5",
    from: "START-OUT",
    to: "TIMER-A1",
    required: true,
    description: "Sambungkan Butang START OUT ke Gelung Timer A1",
    category: "CONTROL",
  },
  {
    id: "rule-c6",
    from: "KM1-A1",
    to: "TIMER-COM",
    required: true,
    description: "Sambungkan Gelung KM1 A1 ke Timer Contact COM (15)",
    category: "CONTROL",
  },
  {
    id: "rule-c7",
    from: "TIMER-NC",
    to: "KM2-A1",
    required: true,
    description: "Sambungkan Timer Contact NC (16) ke Gelung Kontaktor Bintang KM2 A1",
    category: "CONTROL",
  },
  {
    id: "rule-c8",
    from: "TIMER-NO",
    to: "KM3-A1",
    required: true,
    description: "Sambungkan Timer Contact NO (18) ke Gelung Kontaktor Delta KM3 A1",
    category: "CONTROL",
  },

  // --- NEUTRAL BUS ---
  {
    id: "rule-n1",
    from: "N",
    to: "KM1-A2",
    required: true,
    description: "Sambungkan Neutral N ke KM1 A2",
    category: "CONTROL",
  },
  {
    id: "rule-n2",
    from: "N",
    to: "KM2-A2",
    required: true,
    description: "Sambungkan Neutral N ke KM2 A2",
    category: "CONTROL",
  },
  {
    id: "rule-n3",
    from: "N",
    to: "KM3-A2",
    required: true,
    description: "Sambungkan Neutral N ke KM3 A2",
    category: "CONTROL",
  },
  {
    id: "rule-n4",
    from: "N",
    to: "TIMER-A2",
    required: true,
    description: "Sambungkan Neutral N ke Timer A2",
    category: "CONTROL",
  },

  // --- LAMPS ---
  {
    id: "rule-l1",
    from: "START-OUT",
    to: "LAMP-POWER-IN",
    required: true,
    description: "Sambungkan Bekalan Kawalan ke Lampu Penunjuk Kuasa (Power)",
    category: "CONTROL",
  },
  {
    id: "rule-l2",
    from: "KM2-A1",
    to: "LAMP-STAR-IN",
    required: true,
    description: "Sambungkan Gelung KM2 A1 ke Lampu Penunjuk Star",
    category: "CONTROL",
  },
  {
    id: "rule-l3",
    from: "KM3-A1",
    to: "LAMP-DELTA-IN",
    required: true,
    description: "Sambungkan Gelung KM3 A1 ke Lampu Penunjuk Delta",
    category: "CONTROL",
  },
  {
    id: "rule-l4",
    from: "N",
    to: "LAMP-POWER-OUT",
    required: true,
    description: "Sambungkan Neutral N ke Lampu Penunjuk Power",
    category: "CONTROL",
  },
  {
    id: "rule-l5",
    from: "N",
    to: "LAMP-STAR-OUT",
    required: true,
    description: "Sambungkan Neutral N ke Lampu Penunjuk Star",
    category: "CONTROL",
  },
  {
    id: "rule-l6",
    from: "N",
    to: "LAMP-DELTA-OUT",
    required: true,
    description: "Sambungkan Neutral N ke Lampu Penunjuk Delta",
    category: "CONTROL",
  },
];
